### ISSUE TITLE
Error: 'list' object has no attribute 'decode' - when using POST data

### ISSUE THREAD

**Issue by bcoles** [vladko312/SSTImap#1]
`_parse_post` tries to call `urllib.parse_qs()` with the provided POST data as a `list`.

# Reproduce

```
python3 sstimap.py -m POST -u 'http://127.0.0.1/path' --data 'param=value'
```

# Log

Python 3.10.5

```
[!] [sstimap] Error: 'list' object has no attribute 'decode'
Traceback (most recent call last):
  File "/root/Desktop/sstimap/sstimap.py", line 41, in <module>
    raise e
  File "/root/Desktop/sstimap/sstimap.py", line 34, in <module>
    main()
  File "/root/Desktop/sstimap/sstimap.py", line 25, in main
    checks.check_template_injection(Channel(args))
  File "/root/Desktop/sstimap/core/channel.py", line 30, in __init__
    self._parse_post()
  File "/root/Desktop/sstimap/core/channel.py", line 89, in _parse_post
    params_dict_list = parse.parse_qs(self.args.get('data'), keep_blank_values=True)  # <-- here
  File "/usr/lib/python3.10/urllib/parse.py", line 703, in parse_qs
    pairs = parse_qsl(qs, keep_blank_values, strict_parsing,
  File "/usr/lib/python3.10/urllib/parse.py", line 743, in parse_qsl
    qs, _coerce_result = _coerce_args(qs)
  File "/usr/lib/python3.10/urllib/parse.py", line 128, in _coerce_args
    return _decode_args(args) + (_encode_result,)
  File "/usr/lib/python3.10/urllib/parse.py", line 112, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
  File "/usr/lib/python3.10/urllib/parse.py", line 112, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
AttributeError: 'list' object has no attribute 'decode'
```

# Workaround

If only one POST parameter is specified, you can use the following simple workaround:

```diff
diff --git a/core/channel.py b/core/channel.py
index fd7bb52..3568660 100644
--- a/core/channel.py
+++ b/core/channel.py
@@ -86,7 +86,8 @@ class Channel:
 
     def _parse_post(self, all_injectable=False):
         if self.args.get('data'):
-            params_dict_list = parse.parse_qs(self.args.get('data'), keep_blank_values=True)
+            print(self.args.get('data'))
+            params_dict_list = parse.parse_qs(self.args.get('data')[0], keep_blank_values=True)
             for param, value_list in params_dict_list.items():
                 self.post_params[param] = value_list
                 if self.tag in param:
```

**Comment by vladko312** [comment]
Thank you for your feedback.
I would analyze the issue,  as data is supposed to be turned into a string by that point.
Would be fixed in 1.1

**Comment by vladko312** [comment]
Is it fixed in branch `data_list_fix`?

**Comment by bcoles** [comment]
Yes that resolves the issue.

**Comment by vladko312** [comment]
Thank you for your contribution!
