### ISSUE TITLE
SSTImap can't be run outside of it's folder

### ISSUE THREAD

**Issue by sectroyer** [vladko312/SSTImap#18]
If I try to run SSTImap by fullpath or having it in PATH I get this error:
```
 ~/foo/bar/SSTImap-1.1/sstimap.py 

    ╔══════╦══════╦═══════╗ ▀█▀
    ║ ╔════╣ ╔════╩══╗ ╔══╝═╗▀╔═
    ║ ╚════╣ ╚════╗  ║ ║    ║{║  _ __ ___   __ _ _ __
    ╚════╗ ╠════╗ ║  ║ ║    ║*║ | '_ ` _ \ / _` | '_ \
    ╔════╝ ╠════╝ ║  ║ ║    ║}║ | | | | | | (_| | |_) |
    ╚══════╩══════╝  ╚═╝    ╚╦╝ |_| |_| |_|\__,_| .__/
                             │                  | |
                                                |_|
[*] Version: 1.1.0
[*] Author: @vladko312
[*] Based on Tplmap
[!] LEGAL DISCLAIMER: Usage of SSTImap for attacking targets without prior mutual consent is illegal.
It is the end user's responsibility to obey all applicable local, state and federal laws.
Developers assume no liability and are not responsible for any misuse or damage caused by this program
Traceback (most recent call last):
  File "~/foo/bar/SSTImap-1.1/sstimap.py", line 82, in <module>
    load_plugins()
  File "~/foo/bar/SSTImap-1.1/sstimap.py", line 71, in load_plugins
    groups = os.scandir("plugins")
FileNotFoundError: [Errno 2] No such file or directory: 'plugins'
```

**Comment by vladko312** [comment]
Yuo are using sstimap 1.1.0, Can you verify the issue in 1.1.3? Also, can you verify one of your older issues related to cookies?

**Comment by sectroyer** [comment]
Yes, sorry for confusion in 1.1.3 it works correctly :)

**Comment by vladko312** [comment]
Already fixed
