### ISSUE TITLE
[sstimap] Error: 'InteractiveShell' object has no attribute 'channel'

### ISSUE THREAD

**Issue by gjjw** [vladko312/SSTImap#27]
SSTImap (xxx.xxx.com)> eval_code phpinfo()
[!] [sstimap] Error: 'InteractiveShell' object has no attribute 'channel'
Traceback (most recent call last):
  File "/home/kali/SSTImap/sstimap.py", line 58, in <module>
    raise e
  File "/home/kali/SSTImap/sstimap.py", line 51, in <module>
    main()
  File "/home/kali/SSTImap/sstimap.py", line 28, in main
    InteractiveShell(args).cmdloop()
  File "/usr/lib/python3.9/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.9/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/kali/SSTImap/core/interactive.py", line 627, in do_eval_code
    if self.channel.data.get('evaluate_blind'):
AttributeError: 'InteractiveShell' object has no attribute 'channel'
kali@kali:~/SSTImap$

**Comment by gjjw** [comment]
for "info" post detection of injectable point as well. Parrot OS - the same.

**Comment by vladko312** [comment]
Should be fixed in 1.2.0
Can you verify?

**Comment by vladko312** [comment]
Thank you for your feedback!
